export const ROW_SIZE = 15;
export const COLUMN_SIZE = 15;
export const BOARD_SIZE = ROW_SIZE*COLUMN_SIZE;
export const WIN_CONDITION_LENGTH = 5;
export const PLAYER_COUNT = 2;
export const PLACEHOLDER_CHARACTER_IMAGE = "https://msavatar1.nexon.net/Character/BFLBMDNEFEAOMKHMEILKKMFFJJOPAEFECMIPDPMJEGMMPAGLKHHDEHMLALJBEAFKEBNOCLNAIMEGLNLPPOBKICDHPGOKJNBCDCNMGKBHBHADHFEOBGOLCCNKKKOMNGNPDBOKONBOHGAKCFOMIPGECHECELPMCJPNAFOFIJFONDDFPNLAIFMKEKHJKCHKLKCLEGHOEJDFOIDOFIIIPELHAHCJCHALHKPJPHHOKGDAMJECHMCOIIIIJFNCLOINPAPL.png";
export const MAX_NICKNAME_CHAR_LENGTH = 12;
export const BASE_POINTS = 2000;