export const ROW_SIZE = 15;
export const COLUMN_SIZE = 15;
export const BOARD_SIZE = ROW_SIZE*COLUMN_SIZE;
export const WIN_CONDITION_LENGTH = 5;
export const PLAYER_COUNT = 2;
export const PLACEHOLDER_CHARACTER_IMAGE = "https://i.mapleranks.com/u/IGBFKIJEJDKAJAEDPBJIJEPKPPFEEMIBIOHDHFMEIIFJMGBBPHOMFGHPLLPHGCAEKEOLKLDPNDEJNDPMKCJAGHNMKJNNAEICIPDKLIKEHJBPELGLKDAOIHCNFJKGDIKJOJJKPGHNNNIJAKNPJCDLIHBKCLEBLBFNOBFJLKPHKAAFLEFBHEMJPLOEPHIKCNIMBCMIFMGJHIMNJNHNJFDIMNDBLHEANBAIPJBHFGMKKNIAEEHIPAMHEECKIADDKHJG.png";
